dist: trusty
language: go
os: linux

go:
  - 1.12.x
  - master

jobs:
  allow_failures:
    - go: master

install:
  - sudo apt-get update -qq && sudo apt-get install -y -qq apache2-utils php5
  # ensure that vendor/ is in sync with code and Gopkg.*
  - curl https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -L -o ~/dep && chmod +x ~/dep
  - rm -fr vendor/
  - ~/dep ensure -v -vendor-only
  - git diff --exit-code

script:
  - git status
  - go build -v ./cmd/pmm-configure
  - go build -v ./cmd/pmm-configurator
  - go test -coverpkg="github.com/percona/pmm-manage/..." -c -tags testrunmain ./cmd/pmm-configurator
  - |
    sed -i "/ssh-key-path/assh-key-owner: $USER" tests/sandbox/config.yml
  - PATH=$PATH:./tests/sandbox TEST_CONFIG=./tests/sandbox/config.yml ./pmm-configurator.test -test.run "^TestRunMain$" -test.coverprofile=coverage.txt >/dev/null 2>&1 &
  - sleep 1
  - bats --tap tests/*.bats
  - killall -SIGINT pmm-configurator.test

after_success:
  - bash <(curl -s https://codecov.io/bash) -X fix

notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    rooms:
      - secure: i9S5flGm9ZTlxJrbsdfSUoHpTKE0WBIf0xK1hCu5e0N/Vi0BtPjgXuoYZe/q9OkuejF/SG5GqoO6BH2CV+a9SLUA3LMCDuwgH/v83p2ML3CwQJd+v2o9vZG1oNG0gdyatUbdxBKBH0QwQ5QUh14FYyMGI8CEW5B+wv44yf9pHx8F+xJY3tGbxPqUhdXgMbC6SpvoLTp2RNwNCFWN5KoJoGRCtyc5Jigbw8PAfRUvSMnU9G/ZdHom6/dlvkEir1EzIlbPwv+Xq9BAfy/Nn0ra7sFlKDTJyc7HWQbzCaMlQBbP5QAP9T3LagHtsWAhw6xyRdDWrRGkaAS4rnmzbW2qDPL1Ss4nDIWjaqbpYVgHGI8M3RxQjyw7ccD40rPVVyF7nlhFByP/bcURVNZrNbKgezvM8dJVPDndVBHdaP3mHcL/IpR/JF8GYyO3tuclC9uUzCcQtyMkpbJ9/ehFSfTlz3ztka4NPeL9QB6pDUDQJa/DjMuhmfQILB9g77UEA8IR+S4sW2GFeHwZ/lwqKWL020X32zkMVEU+3k8uZ+MoR8u2ILg+Alq2FUbT61vbspcn/YyMmNJr11Zd+aXoE67Km4aZziHWOT8Pra7EMaKtpLxYIx4T9V8jgUD2jZetW8L9EQASjzsbIct4YnG9YVkAMIUi75YnYxLAzSjDlBR8+j0=
